### ISSUE TITLE
Extend Output Parameters

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#122]
This is a necessary stepping stone for #70, in that we want to offer a defined set of outputs from the simulation that can be used to formulate an objective function. We also want to direct this task to any other outputs that might be useful for reporting. There should also be a clear way of "pre-selecting" these outputs for use in a custom objective function (which needs some thought).

The following list should be edited until we have an exhaustive set of outputs that can be reproduced for all study configurations:

* Power Output
* Device Mass
* Device Surface Area
* Mean PTO Force(?)
* Mean Device Displacement(?)

Help with defining this list is required.

**Comment by ryancoe** [comment]
I suggest that we deliver raw (not bulk) values. So, for example, f_PTO (t) - the user can take the mean or max or whatever they like. Additionally, this would mean returning the device dimensions and allowing the user to calculate mass via a function. This will give more modularity to the user.

- Power over time
- PTO force over time
- Wave elevation over time
- Device geometric dimensions
- Design variable values (this might include PTO gearing, etc.)
- State (e.g., position) and input (e.g., PTO force) constraints

**Comment by H0R5E** [comment]
Are the time dependent outputs available for all the controllers, or just PS?

**Comment by ryancoe** [comment]
This was closed with #144.
