### ISSUE TITLE
Modularisation and Data Transfer

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#126]
This is a proposal for an architecture for the library code (i.e WecOptLib) that will provide three benefits. These are:

1. Separation (modularisation) of the major functional components of the code, such that they become solely data coupled. This then allows work to be done within each components without the need to modify or having any effect upon other components.
2. Reliable, documented data structures (data transfer objects) are used to transfer data between the functional components. This provides certainty for a consumer of this data, be that the user or another functional component.
3. Device independence. This framework should not be abstracted per device, provided the devices given are within scope. Abstraction of the functional components for device classes may still be beneficial.

A schematic of this architecture is:

![WecOptTool Components](https://user-images.githubusercontent.com/5088535/79973129-ea56c900-848e-11ea-8b18-e55241bcc547.png)

Data Transfer Objects
-----------------------

At the top of the diagram are the data transfer objects (DTOs). These are fixed APIs that carry data between the major functional components of the tool. An implementation of these would be a public facing class that contains a Struct and a method for populating the struct to check the validity of the inputs.

The three DTOs defined here are:

1. *Environment / Device*: This is populated by the user and the optimiser to define the environmental and device parameters. All inputs required to run the "behaviour" component must be supplied here.
2. *Loadings*: This is populated by the "behaviour" component and contains all the data that is required for the "motion control" component to calculate and control the device motions.
3. *Motions*: This is populated by the "motion control" components and contains all the data required to build a cost function in the "evaluation component".

Functional Components
--------------------------

The lower half of the diagram contains the key functional components of the code and defines the points of separation provided by the DTOs. Ultimately, these components take a DTO as input and return a DTO as output - how they are implemented within the block is not important. However, it is probably useful to structure these in such a way that they are abstracted for different cases, i.e. they are structured to avoid code repetition and lots of if statements. 

The three components defined are:

1. *Behaviour*: this component is responsible for calculating the loadings on the device by calling an external tool (e.g. NEMOH). It can be abstracted for different external tools and may also be useful to abstract it for different device classes (like single body vs multi-body, fixed or floating, etc).
2. *MotionControl*: this component calculates the controlled motion of the device. It is likely to be abstracted per controller and/or per device type, if necessary.
3. *Evaluation*: this component is used for defining a cost function and is likely to be user facing. It is a thin wrapper to allow access to the DTOs so that a cost function can be derived. Some prebaked examples could also be provided.

Device Model
---------------

Not shown on the diagram (it encompasses it) is the device model, which controls the calling of the components and building the DTOs. This could access the DTOs to choose the correct abstraction of a component to use, for instance, given user / optimiser selections or device types, or it could be abstracted if that logic were external (say in WecOptTool). To allow configuration, the optimiser should sit outside of the device model and would modify and pass the 
"Environment / Device" to it, somehow.

Relationship to Current Structure
------------------------------------

The current structure of WecOptLib and this proposal is:

```
+ models <- contains controller and evaluation (strongly coupled to nemoh module) 
+ models.DeviceModelTemplate.m <- Abstraction per device only
+ nemoh <- contains code for calling NEMOH
...
```

The new structure would then look something like:

```
+behaviour <- contains the behaviour component
+behaviour/AbsBehaviour <- base class for all behaviours
+behaviour/@NEMOHBehaviour <- implemented behaviour for NEMOH
+motion <- contains the motion control component
+motion/AbsMotionControl.m <- base class for all controllers
+motion/@PSControl <- implementation for PS control
+models <- contains the device model
+models/AbsDeviceModel.m <- base device model
+models/@NEMOHPSDeviceModel <- if we use abstraction here.
+dto <- contains the DTOs
+dto/EnvDev.m
+dto/Loadings.m
+dto/Motions.m
...
```

The evaluation class would probably go into WecOptTool, and then would be passed into the device model. So we would have:

```
WecOptTool/+evaluation/AbsEvaluation.m <- the user can subclass this
WecOptTool/+evaluation/Power.m <- pre built for power based cost function
```

Drawbacks
------------

The main drawback with this structure relates to modification of the DTOs, which requires careful consideration when they are both generated and consumed by components.

Next Steps
-----------

I would recommend starting this process for a limited part of the code. I think implementing the Evaluation component and the Motions DTO would work towards #70 and #122.

If that is successful then the rest could be applied for #123.

**Comment by ssolson** [comment]
Hey Mat great proposal. Overall I like the idea of modularizing the model more. I think you have proposed a sound way to do that. Where specifically is the NEMOH folder going (I think its EnvDev (which I read as environmental development, I would propose a new name))? My primary concern for this proposal is logistics with respect to priority. This major overhaul of the code will impact work on most if not all the other issues at a minimum through merge conflicts. Where do you stand on priority of this proposal with respect to the other issues/ proposed work on this project?

**Comment by ryancoe** [comment]
@H0R5E - This is a good discussion and I'm general in favor of trying this. My main concerns are 

1. usability/accessibility:  typical MATLAB users, myself included, are not adept programmers :)
2. maintainability: we need to balance the complexity of our coding with the current state of the tool (current state of tool is still quite basic)

I know that you have have a good handle on these things too, just want to emphasize them.

**_I agree that the best way to refine this is to start to implement it and see how it goes._**

**Comment by H0R5E** [comment]
@ssolson, I think maybe you saw the first version of the comment where I accidentally posted it before it was finished. It's been updated now. To answer your questions:

1. The current +nemoh package would go into what I've named "+behaviour", although I'm not sold on any of the names, TBH, and I'd like to iterate them a bit. The `dto.EnvDev` class refers to the "Environment / Device" DTO.
2. I think we put this in alongside the current structure, and use some configuration for switching across until we are happy with it. It might be the result of several PRs.

@ryancoe, thanks for the endorsement. I think the main point is to try and separate the components, so that it's easier to develop them independently. How the components are then structured can be iterated. I agree that we need to keep the complexity manageable, but I do think that classes can sometimes help reduce complexity (beyond the syntax) because it reduces duplication. I also agree that we should do this in small stages, which we can evaluate in parallel to the tool as it stands. I think starting with #70, is a good way to get some of the concepts tested.
