### ISSUE TITLE
Update MATLAB Support to 2020a Update 1

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#133]
MATLAB 2020a Update 1 was released on the [22nd of April](https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/updates/r2020a/r2020a-updates-release-notes.pdf).

We should formally update our support to this version once universally available to the dev team.

**Comment by ryancoe** [comment]
I've updated, all tests passed

```
MATLAB Version: 9.8.0.1359463 (R2020a) Update 1
Operating System: Mac OS X  Version: 10.14.6 Build: 18G4032 
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
```
[test_results.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/4564752/test_results.pdf)
