### ISSUE TITLE
Core: allow for all options of `bounds`

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#148]
See `scipy.optimize.minimize` documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html

**Comment by cmichelenstrofer** [comment]
Bounds allows different input *types*. It can be a `Bounds` class, or a sequence of `(min, max)` pairs, or `None`. I think the only one we don't allow is `(min, max)` right now. There is also the complication that we split it in two (`bounds_wec` and `bounds_opt`) and ideally it should work with any combination of the input options (e.g. 3x3=9 different combinations of input types). Hopefully this is doable in a clean way without having to specify 9 if-else which would be maybe too much
