### ISSUE TITLE
Minor improvements to 'Getting Started' section of the documentation

### ISSUE THREAD

**Issue by mfaltas-sandia** [SNL-WaterPower/WecOptTool#171]
1. Add “The link to the NEMOH repository could be found in the ‘Requirements’ section above” at the beginning of step 3 of the 'Getting Started' section. This is so that the user does not get confused when looking for the NEMOH repository if the user just skipped over to the 'Getting Started' section right away without reading the rest of the documentation. The user could also become confused with the sentence that says "Executables are provided in the 'Release' directory of the NEMOH source code" thinking that there is a specific release of NEMOH that should be downloaded from the 'Releases' section on GitHub.

1. In part 3 of the 'Getting Started' section of the documentation, underneath the section for windows, add "The following commands should be entered into MATLAB command-line interface". This should provide more clarity to the user so that the user does not end up typing these commands into BASH or command prompt.

**Comment by mfaltas-sandia** [comment]
The end product of these minor changes should look something like this:

The changes are in red

![image](https://user-images.githubusercontent.com/70349387/92536817-dcb09e80-f1f7-11ea-9429-ed826df696a5.png)

**Comment by ssolson** [comment]
Hey Mina! Thank you for your helpful suggestions to improve the installation/ getting started experience. I have addressed them in the latest commit (e1de750).
