### ISSUE TITLE
Version 1.0.0 Final Preparations

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#174]
These are the last things we have to do for v1.0.0:

- [x] freeze the code
- [x] freeze the docs
- [x] test code on non-parallel MATLAB install
- [x] create a new release

[test_results_no_pct.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/5245026/test_results_no_pct.pdf)

**Comment by H0R5E** [comment]
@ryancoe @ssolson when #175 #177 and #178 are merged, or at the start of my day tomorrow (2020/9/18), I'm going to freeze the code and docs. After that point, no more additions should be made to master unless to correct something that is obviously wrong. At the start of my day on Tuesday (2020/9/22), I will review and merge any PRs that address such problems, then I will tag the new release.

**Comment by ryancoe** [comment]
I promise to abide by this :)

**Comment by H0R5E** [comment]
@ryancoe, @ssolson - code and docs are frozen

**Comment by H0R5E** [comment]
Done:

https://github.com/SNL-WaterPower/WecOptTool/releases/tag/v1.0.0
