### ISSUE TITLE
show WaveBot case B results in geometry plot

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#178]
@ssolson had a very nice idea about how to show the optimal designs in the WaveBot case B example.

![WaveBot_caseB_geometries](https://user-images.githubusercontent.com/5589887/93491558-1142eb00-f8c7-11ea-90af-3ae3d075c206.png)

**Comment by ryancoe** [comment]
while you're at it, revise legend entry to `Original geometry (Coe et al. 2016)` (note the period)

**Comment by ssolson** [comment]
![image](https://user-images.githubusercontent.com/13438942/93527165-b2e13100-f8f5-11ea-9685-92353a967454.png)

**Comment by H0R5E** [comment]
I think the blue are black lines are incorrectly labelled.

**Comment by ssolson** [comment]
Fixed in f3e65dd
