### ISSUE TITLE
remove sine component of 2-point wave. 

### ISSUE THREAD

**Issue by cmichelenstrofer** [SNL-WaterPower/WecOptTool#181]
Our states `x_wec` (and `x_opt` for the unstructured controller) consist of the Fourier coefficients of the WEC position (and PTO force). We include the mean (DC) component plus the cosine and sine components for each frequency. However, the sine component for the largest frequency has no effect since that sine is evaluated at multiples of pi and is therefor always zero. 

See [this explanation](https://www.oceanopticsbook.info/view/surfaces/level-2/wave-representations) for example:
> The smallest wave that can be captured correctly in a sampling scheme has a period of twice the sampling interval. This called the two-point wave or two-point oscillation. Note that a sine term with period $2\Delta x$ would be sampled at arguments of $0, \pi, 2\pi, \dots$ where the sine is zero and is thus not detectable.

**Comment by cmichelenstrofer** [comment]
Some clarification from our discussion yesterday:

- We **are** using that last sine component because our constraints use `nsubsteps>1` and we use a non-square time matrix. The last sine component does not affect the dynamics (equality constraint) or the objective function, but affects other constraints. 
- An alternative approach is to use a larger number of frequencies and no `nsubsteps>1`. We would then use the FFT which is efficient for large problems. But there is still a question about whether autograd handles the FFT correctly.

Actions:

- [ ] Run the tutorial with 4x more frequencies in the same range (0.25x `f0`) and verify we get similar results. 
- [ ] Verify that autograd can handle the FFT
- [ ] Consider moving to FFT instead of time-matrix and not allowing `nsubsteps`

For now, though, let's remove the sine component.

**Comment by michaelcdevin** [comment]
> Some clarification from our discussion yesterday:
> 
>     * We **are** using that last sine component because our constraints use `nsubsteps>1` and we use a non-square time matrix. The last sine component does not affect the dynamics (equality constraint) or the objective function, but affects other constraints.
> 
>     * An alternative approach is to use a larger number of frequencies and no `nsubsteps>1`. We would then use the FFT which is efficient for large problems. But there is still a question about whether autograd handles the FFT correctly.
> 
> 
> Actions:
> 
>     * [ ]  Run the tutorial with 4x more frequencies in the same range (0.25x `f0`) and verify we get similar results.
> 
>     * [ ]  Verify that autograd can handle the FFT
> 
>     * [ ]  Consider moving to FFT instead of time-matrix and not allowing `nsubsteps`
> 
> 
> For now, though, let's remove the sine component.

These new actions will be tracked in #194.
