### ISSUE TITLE
force_from_impedance() function in core.py

### ISSUE THREAD

**Issue by akeow** [SNL-WaterPower/WecOptTool#186]
Now, it returns `force_from_rao_transfer_function(impedance/(1j*omega), False)`

https://github.com/SNL-WaterPower/WecOptTool/blob/3d9caf446706d2761d5a6c55f69af3c7096b718a/wecopttool/core.py#L1810-L1827

- impedance was defined for velocity input and force output
- when modifying the impedance to switch to displacement as input and force as output, should multiply impedance by `jw`.

**Comment by ryancoe** [comment]
```math
Z_i(\omega) = \frac{\textrm{Force}}{\textrm{Velocity}}
```

**Comment by ryancoe** [comment]
@akeow - We agree that this is a bug. Can you please submit a pull request to fix it? Happy to help you do this.
