### ISSUE TITLE
link Sept. 29 webinar slides

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#190]
We should link(s) to the Sept. 29 webinar slides in one or more of the following locations:

- `README`
- `docs`

**Comment by H0R5E** [comment]
Where are they stored?

**Comment by ryancoe** [comment]
DOI: 10.13140/RG.2.2.16353.94564
https://www.researchgate.net/publication/344455181_WecOptTool_Sept_2020_Webinar?channel=doi&linkId=5f7783c8a6fdcc0086525bcd&showFulltext=true

**Comment by ryancoe** [comment]
We will add a second section on the following page for internal publications and provide a link to the slides via this.

https://snl-waterpower.github.io/WecOptTool/user/references.html
