### ISSUE TITLE
Using TravisCI for testing

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#199]
It looks like TravisCI and CircleCI now both support [MATLAB continuous integration](https://uk.mathworks.com/help/matlab/matlab_prog/continuous-integration-with-matlab-on-ci-platforms.html). I am going to try and get this working for a copy of WecOptTool on my account and I will report the results here.

**Comment by H0R5E** [comment]
OK, so I have it up and running on [H0R5E/WecOptTool-Test](https://github.com/H0R5E/WecOptTool-Test) with the build being successful on the master branch. I then have a [PR](https://github.com/H0R5E/WecOptTool-Test/pull/1) where I have broken the code to check that Travis responds.

Couple of notes on this:
1. It's a bit slow - it's taking about 10 mins to build and test
1. It doesn't seem to be able to run in parallel even though the parallel toolbox is available and there are 2 cores.
1. It only works on linux (for now)

In general, though, I would say this is a good thing to have given it doesn't cost us anything. We can also stop worrying about the Jenkins server on the Sandia network.

Let me know if you want to put it into WecOptTool and I will port the changes over.

**Comment by ryancoe** [comment]
Sounds good. Please proceed.

**Comment by H0R5E** [comment]
Done with 05d7705f0d2685dfe3d2ea6da240660dd2935943 and 396b16610c134ec6e657314bbb8b69dfc18ff600.
