### ISSUE TITLE
ensure real part of diagonals of impedance are positive

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#2]
Due to irregular frequencies and perhaps some other numerical issues, it is possible to get negative values for the radiation damping. This can be valid on the off-diagonals (i.e., the terms that describe interaction between modes of motion and/or different bodies), but it cannot be valid for the diagonals. When negative damping occurs on the diagonals, you no longer have a passive system.

We currently have a default value for friction damping that is added to the diagonals:

https://github.com/SNL-WaterPower/WecOptTool/blob/3933c5ff9dd7320e2dea14a29233d40d32d4d880/WecOptTool/core.py#L75-L79

We should add an additional step that checks whether the diagonals of the impedance matrix have positive real parts, and sets those which are less than zero to zero. It may be good to return a warning that this is happening also.

**Comment by cmichelenstrofer** [comment]
PR #10 shifts the values of the diagonals of linear damping upwards to ensure the minimum is >= some tolerance.
