### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by cmichelenstrofer** [SNL-WaterPower/WecOptTool#23]
The tests currently just test that that the code runs. Now that we have an initial release we should write tests that check that new commits do not inadvertently change the code outputs. 

* use `assert` to verify new versions give same results as previous ones.

**Comment by ryancoe** [comment]
In addition to check for consistency of solution, we should also check against theory. I've done one of these so far:

https://github.com/SNL-WaterPower/WecOptTool/blob/9eb7a90302c649a280a9ce6307fa6d44fd877e73/tests/test_wecopttool.py#L185-L200

Additional good tests that we've done in the past:

- Proportional damping gives same power solution as CC at the resonant frequency of the WEC (~0.625 Hz for the WaveBot)
- Proportional integral (PI) gives same power as CC for any single frequency (regular) wave
- For any point absorber controller, the capture width must be less than the theoretical limit (see, eg., Falnes EQ 6.77)
