### ISSUE TITLE
Feature request: cache deps. for CI/CD

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#35]
https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows

**Comment by cmichelenstrofer** [comment]
Now caching the conda environment with capytaine and wavespectra (and all their dependencies, e.g. numpy, scipy, etc). This will be part of v2.1. When a cache is available this reduces the time to install in ubuntu from ~1.5 minutes to ~15 seconds. On MacOS and Windows there is significant speedup but install still can take long (~5 minutes on Windows!). On Ubuntu almost the netirety of the run time are the tests (~2 minutes).

**Comment by cmichelenstrofer** [comment]
The cache is updated:

- if it is the first time the tests are run that calendar day
- if the `pyproject.toml` file has changed
- if you manually change the `CACHE_NUMBER` value
