### ISSUE TITLE
scaling

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#4]
Since the forces and moments are often on the scale of 1e3 to 1e6 and velocities are on the scale 1e-1 to 1e0, the optimization problem needs some help with scaling... @cmichelenstrofer has already done this elsewhere, just need to apply here. Might be nice if you can make a note on this issue about the logic behind what you've done.

**Comment by ryancoe** [comment]
![image](https://user-images.githubusercontent.com/5589887/131726081-e5661bb3-0307-4e6b-af2f-02d2804c9d6b.png)

**Comment by ryancoe** [comment]
@gbacelli suggested a way to automatically set the scaling (or at least check if it is OK). We basically want to make sure the the motions and forces are of similar scales. We can check the gradient of the `f_i` and `f_{ext}` relative to `x`

![image](https://user-images.githubusercontent.com/5589887/131726383-4fe89382-93f6-45a5-b666-95a1baa5c05a.png)

**Comment by ryancoe** [comment]
@cmichelenstrofer - Please record any resolution on the scaling question that we discussed this morning here for posterity.

**Comment by cmichelenstrofer** [comment]
I ended up removing the `gi_block_scale` because it did not make sense to me to scale only one term in the dynamic equations and not the others.

**Comment by ryancoe** [comment]
I'd like to reopen this and discuss a bit more. In the end, we want/need scaling.

**Comment by cmichelenstrofer** [comment]
We still have scaling for the state variable (can scale WEC dynamics state and controller state separately) and for the objective function.

**Comment by ryancoe** [comment]
Ahhh, ok. Thanks.

**Comment by ryancoe** [comment]
In #48, we introduced a "heads up display" the outputs the mean values of `x_wec`, `x_opt`, and the objective function. This isn't necessarily the perfect thing to base the scaling on. Take, e.g., a regular wave, where all of the components except one or two are zero.
