### ISSUE TITLE
noncoverged PS cases?

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#4]
Let's take a look at these outlier cases and see if the additional outputs from `fmincon` can help us flag these problem cases.

_Originally posted by @ryancoe in https://github.com/SNL-WaterPower/WecOptTool/issues/23#issuecomment-528429216_

https://www.mathworks.com/help/optim/ug/fmincon.html

**Comment by ryancoe** [comment]
As mentioned previously, this can be closed out as soon as we

- [ ] Show that the above described issue w/ negative damping from irregular frequencies is indeed the source of this problem
- [ ] Put in some sort of check that either (1) throws an error, (2) throws a warning, or (3) forces the damping to a non-negative value (probably some discussion is warranted on which of these is appropriate).

**Comment by H0R5E** [comment]
OK so this does not appear to fix #4. I added two tests to `+WecOptLib\+tests\+unit\RM3DeviceModelTest.m` called `testPSNoConverge` and `testPSConverge` where one uses the damping fix and the other doesn't and  `testPSConverge`  errors. Interestingly the first test in that file also fails.

Back to you!
