### ISSUE TITLE
Validate irregular waves (directional and multidirectional)

### ISSUE THREAD

**Issue by cmichelenstrofer** [SNL-WaterPower/WecOptTool#57]
Create validation cases that use irregular waves, both unidirectional and multidirectional. Compare to linear solution.

**Comment by dtgaebe** [comment]
@cmichelenstrofer  Currently, regular_wave() allows the user to specify multiple directions. Should we implement a prevention?

**Comment by cmichelenstrofer** [comment]
@dtgaebe something like this should do the trick:
```python
# check that only a single direction is given
assert len(np.atleast_1d(np.array(direction).squeeze()))==1
```

**Comment by ryancoe** [comment]
@dtgaebe - Seems like this could logically get included in #83. Do you think you could do something like:

```python
t_dom, f_dom , _ = wec.solve(multi_dir_wave)
sol_analytic = np.abs(Fe)**2 / (8*np.real(Zi))
assert f_dom == sol_analytic
```

**Comment by dtgaebe** [comment]
Yes, I'm currently working on this, or rather I was trying to use the `power_limit()` from `core.py`

**Comment by ryancoe** [comment]
Great! Per #69, we are also not sure if `power_limit()` works correctly for multiple DOFs.

**Comment by dtgaebe** [comment]
cosine2s spread function reference:

https://apps.dtic.mil/sti/pdfs/ADA591687.pdf
