### ISSUE TITLE
Wave directionality

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#6]
Our current tensor structures are set up to handle multiple modes of motion, which may arise from a multi-modal device and/or multiple devices within an array. However, we do not currently have a means of handling directional waves. This should be simple enough however and relatively undisruptive to introduce, since the additional dimension needed to handle wave directionality will only show up when calculating the excitation force, after which this dimension is projected into the modes of motion.

**Comment by ryancoe** [comment]
@cmichelenstrofer and I were discussing this more. Key step per this issue is going from `\hat{A}(\omega, \theta)` and `\hat{H}_{ex}` to `\hat{F}_{ex}`.

```latex
&n\textrm{: number of DOFs}\\
&m\textrm{: number of frequencies}\\
&p\textrm{: number of directions}\\
&\textrm{Directional wave spectral density: }S(\omega, \theta) \in \mathcal{R}^{m \times p}\\
&\textrm{Complex amplitude spectrum: }\hat{A}(\omega, \theta) \in \mathcal{C}^{m \times p}\\
&\textrm{Excitation transfer function: }\hat{H}_{ex} \in \mathcal{C}^{n \times m \times p}\\
&\textrm{Complex excitation spectrum: }\hat{F}_{ex} \in \mathcal{C}^{n \times m}\\
&\textrm{Intrinsic impedance: }\hat{Z}_i \in \mathcal{C}^{n \times n \times m}\\
&\textrm{Complex state: }\hat{x} \in \mathcal{C}^{n \times m}
```

<img width="793" alt="image" src="https://user-images.githubusercontent.com/5589887/122605057-27d3c980-d034-11eb-9238-854571be0459.png">

**Comment by cmichelenstrofer** [comment]
PR #10 includes wave directionality.
