### ISSUE TITLE
Move to capytaine 1.2.1

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#7]
I help make some minor updates to `capytaine` that are part of [v1.2.1](https://github.com/mancellin/capytaine/releases/tag/v1.2.1). In particular, there was a bug about the naming of the mass matrix. We should use this latest version of `capytaine` in `WecOptTool`.

changelog: https://github.com/mancellin/capytaine/blob/master/docs/changelog.rst

@cmichelenstrofer - as a general mode of operating, it may often sense to make alterations directly to `capytaine` instead of in `WecOptTool` - I definitely support this

**Comment by cmichelenstrofer** [comment]
The `hydrostatic` module in `capitaine` changed significantly, need to update WEC-Opt tool to use this new module.

**Comment by ryancoe** [comment]
Another note is that `capytaine` 1.2.1 has a method for calculating the impedance: https://github.com/mancellin/capytaine/blob/master/capytaine/post_pro/impedance.py

**Comment by cmichelenstrofer** [comment]
PR  #10 uses `capytaine` v1.3.0
