### ISSUE TITLE
Arbitrary objective function

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#70]
Working through `example.m` to make the git io pages, I realized we don't show how the objective function is set. Let's show this and maybe show two examples.

**Comment by H0R5E** [comment]
@ryancoe I noticed this one just jumped to the top of the tree. Can I ask what has changed?

**Comment by ryancoe** [comment]
@H0R5E - I probably should've made a note of the change (I think we did discuss such a procedure). From now on I will not edit the board except during our meetings.

I see this as one of the key issues to support work on our paper.

**Comment by H0R5E** [comment]
Yes, agreed, but we also need to pin down which outputs we are going to show, because this isn't much use without #122. I'd put that one under this one, or even above.

**Comment by H0R5E** [comment]
I deleted the "high priority" label, as priority is now set by the road map.
