### ISSUE TITLE
Feature request: Allow wave directions to be a subset of the BEM directions.

### ISSUE THREAD

**Issue by dtgaebe** [SNL-WaterPower/WecOptTool#82]
**Feature description.**
Allows the user to define multi-directional waves as long as the incident wave directions are a subset of the wave directions in the BEM solution

**Issue addressed.**
Would also solve #80.

**Comment by cmichelenstrofer** [comment]
To be clear, multidirectional waves were implemented in #10, see #6. However, right now it requires the BEM to have exactly the same directions as the wave. We want the BEM to be able to have more directions than the wave (wave directions subset of BEM directions).

**Comment by dtgaebe** [comment]
Thanks for editing the title @cmichelenstrofer! I implemented the subset functionality in #83, but it needs some formal edits.
