### ISSUE TITLE
Support MHKiT Generated Spectra

### ISSUE THREAD

**Issue by H0R5E** [SNL-WaterPower/WecOptTool#88]
> * Why not use [MHKiT](https://mhkit-software.github.io/MHKiT/) instead of WAFO? This is also developed through WPTO funding and we can modify it as need be to support this program. It would be nice to see WPTO funded projects leverage other WPTO funded projects.

_Originally posted by @kmruehl in https://github.com/SNL-WaterPower/WecOptTool/issues/65#issuecomment-605360662_

Although MHKiT shouldn't replace WAFO as the primary spectrum format, due to its dependency on Python as discussed below, it would be helpful if we were able to support spectra generated by MHKiT users.

This could be as a conversion to WAFO format in MHKit or here in WecOptTool.

**Comment by ssolson** [comment]
The focus of the WecOptTool is on control codesign. At this time given the limited project budget, this feature is seen to offer little to no capabilities over using WAFO. We can revisit/ reopen in the future.
