### ISSUE TITLE
BUG: freq. domain Dataset, power at wrong frequencies

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#91]
While working on #38, we noticed that when plotting the power in the frequency domain, we see nonzero values where we don't expect them. This `xr.Dataset` is produced by taking `fft`'s of the time domain results. The time domain results agree with analytical solutions, so we suspect something wrong with this post-processing workflow.

![output](https://user-images.githubusercontent.com/5589887/161816070-0a71b23f-5050-4945-afea-b50813eb3e77.png)

**Comment by ryancoe** [comment]
@cmichelenstrofer - Can you write up a quick summary of why this is correct and can be closed?

**Comment by cmichelenstrofer** [comment]
For power, the only meaningful value is the zero-frequency component which is the mean power (either into or out of the system). Power is a product of the velocity and force in the time domain, so it is a convolution in the frequency domain, which is why it is not completely intuitive.
