### ISSUE TITLE
WecOptTool Flow Chart

### ISSUE THREAD

**Issue by ssolson** [SNL-WaterPower/WecOptTool#96]
I took an hour to recreate the important aspects of the WecOptTool flow chart in LaTex Tikz. I didn't finish but I wanted to see if Ryan hated it enough to tell me to stop anyway. 

Edit link is here: https://www.overleaf.com/8641328196bhrsbhbfmbrr

**Comment by ssolson** [comment]
@H0R5E 
Ryan & I had a discussion about this for the paper today. Could you take a look for a discussion? This version is trying to walk the line of being useful for both users and laymen. I think we could optimize the layman experience by removing the blocks going into Device, Resource, and controller. And we should probably have one of each e.g. one for the documentation, and one for presentations such as the MEC coming up. Finally, note that once we get close to an agreement I will code it up in Tikz for version control but marked this up in Vizio because its quicker.

![image](https://user-images.githubusercontent.com/13438942/83311359-37cfff80-a1cc-11ea-9cc6-a5e2ccee18d1.png)

[WecOptTool.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/4704691/WecOptTool.pdf)

**Comment by ssolson** [comment]
@H0R5E  Okay, I have iterated the chart with a sideways rotation, added what the kids are calling "swimlanes", and a little color.

 I am looking to see if we can generally agree on this implementation still and therefore seeking high-level feedback (I know not everything is perfectly aligned). Specifically 
    1. Do we like the chart layout? 
    2. Do we like the amount of detail (e.g. where should there be more or less)?
    3. Of the provided details do we like the text I used in the lanes, boxes, and arrows? 
    4. Do you like that the lanes have color and that the arrow matches the lane color? 

And of course any other general/high-level feedback.

![image](https://user-images.githubusercontent.com/13438942/83813513-c0dab100-a67a-11ea-96ee-2921272eb95b.png)

[WecOptTool.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/4732884/WecOptTool.pdf)

**Comment by ryancoe** [comment]
@ssolson - Kudos on this, I think it is looking very nice!

1. Yes, but I would prefer to have the geometry and PTO blocks in the upper left hand corner if possible.
2. I think this is the right level
3. Not sure what you're asking
4. I would have the lines just be black I think..

It is hard to tell that the optimization routine can adjust both geometry and PTO (but not kinematics)

**Comment by H0R5E** [comment]
Sterling, I like it. Personally, I think I would reflect it in the horizontal axis (i.e. flip the locations of the objective function and controller / seastates, etc) to get a clockwise control flow again. Secondly, regarding the lines, you might consider having two types - one for data flow and one for control flow - so that the order of operations is clearer, but it's not a deal breaker.

**Comment by ssolson** [comment]
Okay, a quick iteration to get the Geometry & PTO in the top right and make the flow of the chart clockwise. Lines are all black now although they look took thick so I will decrease that.

Mat and I had a discussion about showing that the optimization routine is interacting with /calling the solvers. To me, this is implicit in the way the line connect and I think the line would add more clutter than clarity). However, it is worth discussing on if we want to include in the paper or not. 

Lastly, Mat and I discussed changing the boxes to deliberate between inputs and processes.

@ryancoe let me know what you think. This is probably ready for another external review e.g. Jesse.

![image](https://user-images.githubusercontent.com/13438942/84169512-edede180-aa35-11ea-8649-9482bc766435.png)

**Comment by H0R5E** [comment]
Yeah, definitely better going clockwise.

**Comment by ryancoe** [comment]
Wouldn’t the optimization routine qualify as a solver?

**Comment by ssolson** [comment]
Agreed it is a solver. I also decreased the line thickness.

![image](https://user-images.githubusercontent.com/13438942/84189030-cc9aee80-aa51-11ea-8c4b-fb13ad78f8b2.png)

**Comment by ssolson** [comment]
**Option 2** to help declutter the lines. In this version, the optimization routine has a bi directional arrow.

![image](https://user-images.githubusercontent.com/13438942/84189503-9a3dc100-aa52-11ea-97b5-4fc028236f13.png)

**Comment by ssolson** [comment]
A couple of clean-ups to the figure.
![image](https://user-images.githubusercontent.com/13438942/85049939-98f74d00-b152-11ea-9d46-3654ddd30fd7.png)

[WecOptToolOriginal.pdf](https://github.com/SNL-WaterPower/WecOptTool/files/4800020/WecOptToolOriginal.pdf)

**Comment by ryancoe** [comment]
@ssolson - please post final PDF and source here. Also add a SVG to replace the diagram here: https://snl-waterpower.github.io/WecOptTool/user/example.html

**Comment by ssolson** [comment]
Zip contains final Visio file, PDF, and SVG. GItHub does not allow Visio 

[WecOptToolFlowChart.zip](https://github.com/SNL-WaterPower/WecOptTool/files/4898447/WecOptToolFlowChart.zip)
