### ISSUE TITLE
Intuitive hydrostatics

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#97]
With #49, we have a conistent way of handling's hydrostatics, buoyancy. However, want to consider:

- is this as intuitive as possible
- can we use capytaine's upcoming hydrostatics module (https://github.com/mancellin/capytaine/pull/106)?

**Comment by ryancoe** [comment]
One thing we did not previously appreciate is that **_you do really need to be at equilibrium_** (if you are not, BEM and/or you transfer functions will not be accurate)...

- our previous work (#49) was at least partially premised on allowing for non-zero mean positions
- our whole process of operating on position instead of velocity and having a zero frequency component (#86) was based on this

**Comment by cmichelenstrofer** [comment]
v2 uses the new Capytaine hydrostatics. These however are currently changing, e.g. capytaine/capytaine#215, so will need to review in the future.

**Comment by cmichelenstrofer** [comment]
Closing this for now. We are using Capytaine's functions in v2.0. I will add the buoyancy topic to the _Discussion_ on zero-frequency component.
