### ISSUE TITLE
PTO/electrical power tutorial

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/WecOptTool#99]
Because it is so crucial, we should update our examples to consider electrical power. Tentative plan:

- `tutorial_1_wavebot.ipynb`: mechanical power and electrical power
- `tutorial_2_wavebot_optimization.ipynb`: just electrical power

Do after or in conjunction w. #95.

**Comment by cmichelenstrofer** [comment]
completed/fixed in v2.0
